A place to put toymodels (doc/toymodels/)
deepmodeling/dpgen pull request #432
Opened 2021-06-09 03:51 UTC by tuoping

1. Made directory doc which sphinx-build configurations; 
2. Made directory doc/toymodels;
3. Automatic listing of files in directory doc/toymodels by rst and sphinx-build.
Preview here:
https://dpgen-testtutorial.readthedocs.io/en/devel/

By the way, our docs are currently deployed on readthedocs. Do we want to move them to github?

2021-06-09 23:32 UTC, amcadmus requested changes

2021-06-09 23:32 UTC, amcadmus commented on doc/index.rst
> +DeePMD-kit's documentation
should be dpgen

2021-06-10 10:00 UTC, AnguseZhang commented
I have a concern. Do you intend to put models in DP-GEN's code repo?  But it will make DP-GEN's code too big, since one model could be larger than several Mb. What TF does is to create a repo for docs. https://github.com/tensorflow/docs

2021-06-11 14:31 UTC, tuoping commented
That's exactly what I mean by "move docs to github". We can open a new branch just for docs and examples.

2021-06-11 16:50 UTC, njzjz commented
Do you mean using GitHub Actions and GitHub Pages to host documents?

2021-06-14 07:41 UTC, amcadmus commented
> That's sort of what I mean by "move docs to github". We can open a new branch just for docs and examples. A repo specifically for docs is fairly common as well. However, our community is relatively diverse, which means double repo for each project, one for code and another for docs. I don't think that's a good idea.

Could you plz explain the benefit of using a separate repo for doc?

2021-06-14 10:08 UTC, njzjz approved these changes

2021-06-15 03:17 UTC, tuoping commented
> Do you mean using GitHub Actions and GitHub Pages to host documents?

Yes.


> > That's sort of what I mean by "move docs to github". We can open a new branch just for docs and examples. A repo specifically for docs is fairly common as well. However, our community is relatively diverse, which means double repo for each project, one for code and another for docs. I don't think that's a good idea.
> 
> Could you plz explain the benefit of using a separate repo for doc?

Actually, I don't think a separate repo for doc is a good idea. A separate branch is more practical. The benefit of a separate branch is more centralized DNS management. Although it's not necessary, we can simply change the domain name of readthedocs page.

2021-06-15 03:19 UTC, tuoping commented
> Do you mean using GitHub Actions and GitHub Pages to host documents?

Yes.


> > That's sort of what I mean by "move docs to github". We can open a new branch just for docs and examples. A repo specifically for docs is fairly common as well. However, our community is relatively diverse, which means double repo for each project, one for code and another for docs. I don't think that's a good idea.
> 
> Could you plz explain the benefit of using a separate repo for doc?

Actually, I don't think a separate repo for doc is a good idea. A separate branch is more practical. The benefit of a separate branch is more centralized DNS management. Although it's not necessary, we can simply change the domain name of readthedocs page.

2021-06-16 08:59 UTC, tuoping commented
After a brief discussion with tansongchen. We think it's more convenient to use readthedocs. So that we don't have to maintain a workflow for doc.

2021-06-16 22:28 UTC, njzjz commented
readthedocs supports to add a project into another one as a subproject, and they will share the same domain. Do you think it's a good idea to make dpgen as a sub-project as deepmd-kit (or we create a new one as the main project)?

2021-06-17 01:27 UTC, tuoping commented
I vote "create a new one".

2021-06-18 08:36 UTC, amcadmus commented
> 
> 
> readthedocs supports to add a project into another one as a subproject, and they will share the same domain. Do you think it's a good idea to make dpgen as a sub-project as deepmd-kit (or we create a new one as the main project)?

dpgen is not a subject of deepmd-kit

2021-06-18 08:40 UTC, amcadmus commented
Now the RTD page is blank. Is this PR a preparation for a serious construction of the RTD page?

2021-06-18 12:06 UTC, njzjz commented
How about creating a new repository called `docs`, which only contains links to other documents or something else?

@tuoping Yesterday I gave you the access to the current documents.

2021-06-19 10:23 UTC, tuoping commented
According to the document of RTD. The first step to set up custom domain seems to require a change in the DNS of our home page "https://deepmodeling.org/".@njzjz

In order to setup your custom domain, follow these steps:
1. For a subdomain like docs.example.com, add a CNAME record in your DNS that points the domain to readthedocs.io. For a root domain like example.com use an ANAME or ALIAS record pointing to readthedocs.io.
2. ……

2021-06-19 10:25 UTC, tuoping commented
I have built a test page here https://dpgen-testtutorial.readthedocs.io/en/devel/
@amcadmus If you think it works, we can go with this.

2021-06-19 14:06 UTC, njzjz commented
> According to the document of RTD. The first step to set up custom domain seems to require a change in the DNS of our home page "https://deepmodeling.org/". @njzjz 
> 
> 
> 
> In order to setup your custom domain, follow these steps:
> 
> 1. For a subdomain like docs.example.com, add a CNAME record in your DNS that points the domain to readthedocs.io. For a root domain like example.com use an ANAME or ALIAS record pointing to readthedocs.io.
> 
> 2. ……

You can use docs.deepmodeling.org.

2021-06-21 00:58 UTC, tuoping commented
Is the CNAME record added in deepmodeling.org for docs.deepmodeling.org? Because it's not working. The custom domain name docs.deepmodeling.org is configured on readthedocs. But docs.deepmodeling.org is still 404.

2021-06-26 00:35 UTC, njzjz commented
> Is the CNAME record added in deepmodeling.org for docs.deepmodeling.org? Because it's not working. The custom domain name docs.deepmodeling.org is configured on readthedocs. But docs.deepmodeling.org is still 404.

This domain is not maintained by me... I think it's @tansongchen

2021-07-15 03:39 UTC, merged