fix NSW value in INCAR; fix local_root check
deepmodeling/dpgen pull request #464
Opened 2021-07-15 07:09 UTC by felix5572

fix NSW value in INCAR; fix local_root check

2021-07-15 12:05 UTC, amcadmus approved these changes

2021-07-15 12:06 UTC, amcadmus requested changes

2021-07-15 12:06 UTC, amcadmus commented on examples/init/INCAR_methane.rlx
> +NSW=0
Why setting NSW=0 in a relaxation INCAR? With NSW=0 the configuration will not be relaxed.

2021-07-15 12:22 UTC, felix5572 commented
Oh, I mistook it as single frame calculation.
And the parameter NSW  will only repeat the single frame calculation many times when IBRION=-1.


in vasp docs:
Description: IBRION determines how the ions are updated and moved.
IBRION=-1: no update.
IBRION=2: ionic relaxation (conjugate gradient algorithm).

2021-07-16 01:30 UTC, amcadmus approved these changes

2021-07-16 01:30 UTC, merged