Add .github/workflow/mirror_to_gitee.yml
deepmodeling/dpgen pull request #475
Opened 2021-07-21 04:12 UTC by tuoping

I found the problem. I've been invoking action in my personal repository: github.com/tuoping/dpgen. So the ssh-private-key in organization deepmodeling cannot be visited. We have to test the action after PR.

2021-07-21 04:14 UTC, tuoping commented
In addition, may I ask how did you enable to sync issue from gitee to github?

2021-07-21 04:35 UTC, njzjz requested changes

2021-07-21 04:35 UTC, njzjz commented on .github/workflows/mirror_gitee.yml
> +          source-repo: "http://github.com/deepmodeling/dpgen.git"
use https instead of http
```suggestion
          source-repo: "https://github.com/deepmodeling/dpgen.git"
```

2021-07-21 04:38 UTC, njzjz commented
> In addition, may I ask how did you enable to sync issue from gitee to github?

A simple method... Set up [this bot](https://fire.fundersclub.com) and then forward the Gitee notification emails to it.

2021-07-21 05:58 UTC, tuoping commented
Sorry about that. But this action still failed with the same error message in my repository tuoping/dpgen. I still think the action need to be invoked in deepmodeling/dpgen.

2021-07-21 18:47 UTC, njzjz commented
Did you set the secret in your own repo?

2021-07-23 09:00 UTC, tuoping commented
The point of this is to test the secret in organization. That's not a bad idea though, to set the secret in my own repo and PR with the mirror_to_gitee.yml file. This way the secret in organization will be of no use.

2021-07-23 21:34 UTC, njzjz commented
If you want to test the secret in organization, you need to push the branch into the organization repository. (or ask someone who has the access to help you)

2021-07-28 01:19 UTC, merged