Create Performing the Run process.md
deepmodeling/dpgen pull request #714
Opened 2022-04-25 03:56 UTC by LiangWenshuo1118

Description of the steps and output files in the DP-GEN run process.

2022-04-25 08:10 UTC, AnguseZhang commented
I've provided my suggestions with @LiangWenshuo1118.

2022-04-27 06:53 UTC, njzjz requested changes

2022-04-27 06:53 UTC, njzjz commented on doc/run/Overview-of-the-run-process.md
> +```
```suggestion
```sh
```
See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

2022-04-27 06:53 UTC, njzjz commented on doc/run/example-of-param.md
> +```
```suggestion
```json
```

2022-04-30 20:54 UTC, njzjz reviewed
Can you add these doc to `doc/index.rst`?

2022-04-30 20:54 UTC, njzjz commented on doc/run/example-of-machine.md
> +In machine parameters, "batch_type" specifies the type of job scheduling system. If there is no job scheduling system, we can use the "Shell" to perform the task. "context_type" specifies the method
```suggestion
In machine parameters, "batch_type" specifies the type of job scheduling system. If there is no job scheduling system, we can use the "Shell" to perform the task. "context_type" specifies the method of data transfer, and "local" means copying and moving data via local file storage systems (e.g. cp, mv, etc.). In DP-GEN, the paths of all tasks are automatically located and set by the software, and therefore "local_root" is always set to "./". The input file for each task will be sent to the "remote_root" and the task will be performed there, so we need to make sure that the path exists.
```

`. /` -> `./` (remove space)

2022-04-30 20:54 UTC, njzjz commented on doc/run/example-of-machine.md
> +In the machine parameter, "context_type" is modified to "SSHContext" and "batch_type" is modified to "PBS". It is worth noting that "remote_root" should be set to an accessible path on the remote PBS
```suggestion
In the machine parameter, "context_type" is modified to "SSHContext" and "batch_type" is modified to "PBS". It is worth noting that "remote_root" should be set to an accessible path on the remote PBS cluster. "remote_profile" is added to specify the information used to connect the remote cluster, including hostname, username, port, etc. 
```
Password should be discouraged. Instead, we should encourage SSH keys in the doc.

2022-04-30 20:54 UTC, njzjz commented on doc/run/example-of-param.md
> +Here, 4 DP models will be trained in `00.train`. Detailed explanation of training parameters can be found at [DeePMD-kit’s documentation](https://docs.deepmodeling.com/projects/deepmd/en/master/).
Provide the specific page instead.

2022-04-30 20:54 UTC, njzjz commented on doc/run/overview-of-the-run-process.md
> +If the process of DP-GEN stops for some reason, DP-GEN will automatically recover the main process by record.dpgen. You may also change it manually for your purpose, such as removing the last iterati
```suggestion
If the process of DP-GEN stops for some reasons, DP-GEN will automatically recover the main process by record.dpgen. You may also change it manually for your purpose, such as removing the last iterations and recovering from one checkpoint.
```

2022-05-09 00:28 UTC, njzjz commented
1. For maintenance, it's better to submit the original script instead of the generated doc.
2. It's better to separate it into a new PR instead of doing all things in a single PR.

2022-05-22 03:14 UTC, njzjz approved these changes

2022-05-30 13:59 UTC, AnguseZhang approved these changes

2022-05-31 00:41 UTC, merged