Support several CALYPSO run in different pressure in one iteration
deepmodeling/dpgen pull request #814
Opened 2022-07-22 01:54 UTC by wangzyphysics

Support several CALYPSO run in different pressure in one iteration:

One can do this by changing `model_devi_jobs` into  
```
{"times":[4, 5],
"NameOfAtoms":["Mg","Al","Cu"],
"NumberOfAtoms":[1,1,1],
"NumberOfFormula":[1,1],
"Volume":30,
...
"PSTRESS":[0, 400, 500, 600],
"fmax":0.01}
```

the `PSTRESS` is a `List` which can contain several different pressure and the number of CALYPSO Loop is same as the length of `PSTRESS` in one iteration

here is picture of this situation

```
$ pwd
/home/zhenyu/workplace/dpgen/debug/iter.000004/01.model_devi
```
![image](https://user-images.githubusercontent.com/76582286/180343696-cf97bff9-fb01-4753-9e1d-d6ae3a6c679e.png)

the `times` is a `List` which can be seen as a collection of  `iter number`, in this example `"times":[4, 5]` means iter.000004 and iter.000005 will run the same CALYPSO Loop

2022-07-23 01:28 UTC, wanghan-iapcm requested changes

2022-07-23 01:28 UTC, wanghan-iapcm commented on dpgen/generator/lib/make_calypso.py
> +    assert pstress != None  or type(pstress) == type(200) or type(pstress) == type(0.001)
similar issue

2022-07-23 01:28 UTC, wanghan-iapcm commented on dpgen/generator/lib/make_calypso.py
> +def _make_model_devi_buffet(jdata,caly_run_opt_path):
I would prefer the original variable name, which is self-explanatory to the readers. It is not easy to relate `caly` to `calypso`...

2022-07-23 01:28 UTC, wanghan-iapcm commented on dpgen/generator/run.py
> +        elif run_mode == 2:
add a comment explaining what does the run_modes mean?

2022-07-24 20:10 UTC, njzjz commented on dpgen/generator/lib/run_calypso.py
> +        sys.exit()
Use `raise` instead

2022-08-03 00:56 UTC, wanghan-iapcm commented on dpgen/generator/run.py
> +        caly_run_opt_path = []
```suggestion
        calypso_run_opt_path = []
```
To improve the readability of the code

2022-08-04 00:32 UTC, wanghan-iapcm approved these changes

2022-08-04 00:34 UTC, wanghan-iapcm commented
Could you please merge the devel branch to fix the bug in UT? Thanks!

2022-08-05 19:40 UTC, njzjz approved these changes

2022-08-06 00:28 UTC, merged