Create DP-GEN Structure.md
deepmodeling/dpgen pull request #844
Opened 2022-08-05 05:03 UTC by HuangJiameng

A basic user guide.

2022-08-05 07:18 UTC, njzjz reviewed
The file needs to be added to TOC in `index.rst`, otherwise it will not be shown in the website.

2022-08-09 03:02 UTC, HuangJiameng commented
> The file needs to be added to TOC in `index.rst`, otherwise it will not be shown in the website.

OK, it is added.

2022-08-09 06:24 UTC, njzjz requested changes

2022-08-09 06:24 UTC, njzjz commented on doc/overview/DP-GEN-structure.md
> +It is strongly recommended that you use the `find in files` function of Virtual Studio software, or similar functions of other software. Type in the name of the parameter you're looking for, and you'
Do you mean **Visual** Studio?

2022-08-09 06:24 UTC, njzjz commented on doc/overview/DP-GEN-structure.md
> +If you have special requirements, you can make personalized modifications in the code corresponding to the function. If you think your modification can benefit the public, and it does not conflict wi
requist -> request

2022-08-09 20:27 UTC, njzjz approved these changes

2022-08-12 01:43 UTC, merged