Add a Troubleshooting.md file
deepmodeling/dpgen pull request #888
Opened 2022-08-18 09:09 UTC by Anopaul

2022-08-18 13:35 UTC, HuangJiameng approved these changes

2022-08-18 21:41 UTC, njzjz requested changes

2022-08-18 21:41 UTC, njzjz commented on doc/troubleshooting/Troubleshooting.md
> +2. Please verify the directories of `sys_configs`. If there isnt's any POSCAR for `01.model_devi` in one iteration, it may happen that you write the false path of `sys_configs`.
typo: isnt’s

2022-08-19 03:18 UTC, njzjz approved these changes

2022-08-20 02:40 UTC, merged