add init-bulk in dpgen documents
deepmodeling/dpgen pull request #907
Opened 2022-08-22 10:42 UTC by baihuyu12

2022-08-22 21:08 UTC, njzjz requested changes

2022-08-22 21:08 UTC, njzjz commented on doc/init/init-bulk.md
> +## Init: Preparing Initial Data
TOC looks like a mass.
![image](https://user-images.githubusercontent.com/9496702/186019321-eff99c63-d3c5-42ec-bcbd-369cdb712016.png)

2022-08-24 02:07 UTC, njzjz approved these changes

2022-08-24 02:07 UTC, njzjz commented on doc/init/init-bulk.md
> +| atom_masses | List of float | [24] | List of atomic masses of elements. The order should be the same as `Elements`. Only useful if `init_fp_style` is "ABACUS".
This table should be generated automatically by `dargs`. But I don't request it done by this PR.
cc @HuangJiameng

2022-08-26 04:00 UTC, njzjz commented on doc/init/init-bulk.md
> +`init_bulk` support both VASP and ABACUS for first-principle calculation. You can choose the software by specifying the key `init_fp_style`. If `init_fp_style` is not specified, the default software
support -> supports

2022-08-27 07:11 UTC, AnguseZhang approved these changes

2022-08-28 04:31 UTC, njzjz approved these changes

2022-08-28 15:33 UTC, AnguseZhang commented
![Screen Shot 2022-08-28 at 11 30 56 PM](https://user-images.githubusercontent.com/38939321/187082013-061dcb52-095e-4a83-abc6-3d31283b89c4.jpg)
Han and I both confronted such strange problem. We don't know how to solve it currently. Does it works fine in your place? @njzjz If so, please merge the PR directly. Otherwise, we may create a new PR.  Thanks.

2022-08-28 19:29 UTC, merged

2022-08-28 19:30 UTC, njzjz commented
I have the same issue but I can merge it on app.